language: python
matrix:
  include:
    - python: 3.8
      dist: bionic
      sudo: true
install:
  - pip install -r tests_requirements.txt
  - pip install coveralls
  - gem install mdl
script:
  - coverage run -m unittest discover
  - black --check canvasaio tests
  - flake8 canvasaio tests
  - mdl . .github
  - python scripts/alphabetic.py
  - python scripts/find_missing_kwargs.py
after_success:
  - coveralls
deploy:
  provider: pypi
  username: "spapadim"
  password:
    secure: TODO_XXX
  on:
    tags: true
  skip_existing: true
